SUPABASE_URL = "https://iejstzzhbtxppwufmrjl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllanN0enpoYnR4cHB3dWZtcmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTQ5ODIsImV4cCI6MjA2Mjg5MDk4Mn0.22LbenqwJBpyGAdb_u5ZYsB5AlHsezLpZCCBGRyAKuA"
